[package]
name = "feedback-fusion"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aliri = "0.6.2"
aliri_axum = "0.3.0"
aliri_clock = "0.1.4"
aliri_oauth2 = "0.10.0"
aliri_tower = "0.5.0"
async-trait = "0.1.77"
axum = "0.6.20"
chrono = { version = "0.4.31", features = ["serde"] }
derivative = "2.2.0"
envy = "0.4.2"
getset = "0.1.2"
kanal = "0.1.0-pre8"
lazy_static = "1.4.0"
nanoid = "0.4.0"
openidconnect = "3.4.0"
paste = "1.0.14"
rbatis = "4.4.20"
rbdc-pg = { version = "4.4.19", optional = true }
rbdc-mysql = { version = "4.4.19", optional = true }
rbs = "4.4.3"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = ["limit", "buffer"] }
tower-http = { version = "0.4.4", features = ["trace"] }
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
typed-builder = "0.18.0"
utoipa = { version = "4.1.0", features = ["yaml", "chrono"] }
validator = { version = "0.16", features = ["derive"] }
version-compare = "0.1.1"

[dev-dependencies]
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["json"] }
test-log = "0.2.14"

[features]
default = ["all-databases"]

docs = []
all-databases = ["postgres", "mysql"]
postgres = ["rbdc-pg"]
mysql = ["rbdc-mysql"]

test = []

