[tasks.docs_init]
command = "pnpm"
args = ["i"]

[tasks.dev_build]
command = "cargo"
args = ["build"]

[tasks.docs_preview]
dependencies = ["docs_init", "dev_build"]
command = "npx"
args = ["redocly", "preview-docs", "target/openapi.yaml"]

[tasks.docs_lint]
dependencies = ["dev_build"]
command = "npx"
args = ["redocly", "lint", "target/openapi.yaml"]

[tasks.docs_build]
dependencies = ["docs_lint"]
command = "npx"
args = ["redocly", "build-docs", "target/openapi.yaml", "-o", "docs/index.html"]
