[package]
name = "feedback_fusion_codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
syn = { version = "2.0.71", features = ["full"] }
quote = "1.0.36"
