[package]
name = "feedback-fusion-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { features = ["derive"], version = "1.0.219" }
thiserror = "2.0.12"
tracing = "0.1.39"
tracing-opentelemetry = { version = "0.25.0", optional = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { features = ["full"], version = "1.46.1" }
tokio-retry = "0.3.0"
tonic = "0.13.1"
prost-types = "0.14.1"
