apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feedback-fusion.fullname" . }}
  labels:
    {{- include "feedback-fusion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "feedback-fusion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "feedback-fusion.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "feedback-fusion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 8000 
              protocol: TCP
          env:
            - name: RUST_LOG 
              value: {{ .Values.feedbackFusion.log }}
            - name: FEEDBACK_FUSION_CONFIG
              value: /etc/config/config.yaml
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.api.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

            - name: {{ .Values.feedbackFusion.config.secret }}
              mountPath: /etc/config
      volumes:
        {{- with .Values.api.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        - name: {{ .Values.feedbackFusion.config.secret }}
          secret:
            secretName: {{ .Values.feedbackFusion.config.secret }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
