{{- if .Values.feedbackFusion.preset.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.feedbackFusion.preset.name }}
data:
  {{- with .Values.feedbackFusion.preset.data }}
  config.yaml: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
