{{- if .Values.feedbackFusion.preset.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.feedbackFusion.preset.name }}
data:
  {{- if .Values.feedbackFusion.preset.data }}
  config.yaml: |
    {{ .Values.feedbackFusion.preset.data | indent 4 }}
  {{- end }}
{{- end }}
