apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedback-fusion.fullname" . }}
  labels:
    {{- include "feedback-fusion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "feedback-fusion.selectorLabels" . | nindent 4 }}
