[package]
name = "feedback_fusion_common"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"
prost = "0.12.4"
prost-types = "0.12.4"
validator = "0.18.1"

[build-dependencies]
tonic-build = "0.11.0"
