// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckboxStyle } from "./CheckboxStyle";

export interface CheckboxOptions { defaultState: boolean, style: CheckboxStyle, }