// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackPromptInputOptions } from "./FeedbackPromptInputOptions";
import type { FeedbackPromptInputType } from "./FeedbackPromptInputType";

export interface CreateFeedbackPromptFieldRequest { title: string, type: FeedbackPromptInputType, options: FeedbackPromptInputOptions, }