// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RatingResponse } from "./RatingResponse";
import type { TextResponse } from "./TextResponse";

export type FeedbackPromptFieldData = TextResponse | RatingResponse;