// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckboxOptions } from "./CheckboxOptions";
import type { NumberOptions } from "./NumberOptions";
import type { RangeOptions } from "./RangeOptions";
import type { RatingOptions } from "./RatingOptions";
import type { SelectionOptions } from "./SelectionOptions";
import type { TextOptions } from "./TextOptions";

export type FeedbackPromptInputOptions = { "type": "text" } & TextOptions | { "type": "rating" } & RatingOptions | { "type": "checkbox" } & CheckboxOptions | { "type": "selection" } & SelectionOptions | { "type": "range" } & RangeOptions | { "type": "number" } & NumberOptions;