// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FeedbackPrompt { id: string, title: string, target: string, active: boolean, updated_at: Date, created_at: Date, }