// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckboxResponse } from "./CheckboxResponse";
import type { NumberResponse } from "./NumberResponse";
import type { RangeResponse } from "./RangeResponse";
import type { RatingResponse } from "./RatingResponse";
import type { SelectionResponse } from "./SelectionResponse";
import type { TextResponse } from "./TextResponse";

export type FeedbackPromptFieldData = { "type": "text" } & TextResponse | { "type": "rating" } & RatingResponse | { "type": "checkbox" } & CheckboxResponse | { "type": "selection" } & SelectionResponse | { "type": "range" } & RangeResponse | { "type": "number" } & NumberResponse;