// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RatingOptions } from "./RatingOptions";
import type { TextOptions } from "./TextOptions";

export type FeedbackPromptInputOptions = TextOptions | RatingOptions;