// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FeedbackTarget { id: string, name: string, description: string | null, updated_at: Date, created_at: Date, }