// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackPromptFieldResponse } from "./FeedbackPromptFieldResponse";

export type GetFeedbackPromptResponsesResponseWrapper = Record<string, Array<FeedbackPromptFieldResponse>>;