// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackPromptField } from "./FeedbackPromptField";

export interface Page<T> { records: Array<T>, total: bigint, page_no: bigint, }