// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackPromptInputOptions } from "./FeedbackPromptInputOptions";

export interface PutFeedbackPromptFieldRequest { title: string | null, options: FeedbackPromptInputOptions | null, }