name: Continuous integration

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push: 
    branches:
      - main

jobs:
  dashboard_build:
    name: dashboard-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Dashboard build
        run: make dashboard_build

  lib_build:
    name: lib-build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Lib build
        run: make lib_build 

  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run check
        run: make check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: make clippy 

  test:
    needs: [clippy, check]
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [postgres, mysql, mariadb, mssql, unittest, distributed_caching]
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Tests
        run: make ${{ matrix.test }}
