name: Publish library 

on:
  push:
    tags:
      - "lib-*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm i
        working-directory: lib

      - name: Build
        run: pnpm run build
        working-directory: lib

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          package: lib
          access: public
          token: ${{ secrets.NPM_TOKEN }}
